const colleges = {
  Alberta: [
    "Ambrose University",
    "Burman University",
    "Concordia University of Edmonton",
    "Grant MacEwan University",
    "King's University College",
    "MacEwan University",
    "Mount Royal University",
    "Northern Alberta Institute of Technology",
    "Red Deer Polytechnic",
    "Southern Alberta Institute of Technology",
    "University of Alberta",
    "University of Calgary",
    "University of Lethbridge"
  ],
  BritishColumbia: [
    "British Columbia Institute of Technology",
    "Capilano University",
    "College of New Caledonia",
    "College of the Rockies",
    "Columbia College",
    "Douglas College",
    "Emily Carr University of Art + Design",
    "Kwantlen Polytechnic University",
    "Langara College",
    "North Island College",
    "Northern Lights College",
    "Okanagan College",
    "Selkirk College",
    "Sprott Shaw College",
    "Thompson Rivers University",
    "Trinity Western University",
    "University of British Columbia",
    "University of Northern British Columbia",
    "University of the Fraser Valley",
    "University of Victoria",
    "Vancouver Community College",
    "Vancouver Island University"
  ],
  Manitoba: [
    "Assiniboine Community College",
    "Booth University College",
    "Brandon University",
    "Canadian Mennonite University",
    "Manitoba Institute of Trades and Technology",
    "Red River College Polytechnic",
    "Robertson College",
    "St. Andrew's College",
    "St. Paul's College",
    "University College of the North",
    "University of Manitoba",
    "University of Winnipeg"
  ],
  NewBrunswick: [
    "Atlantic Business College",
    "Canadian School of Natural Nutrition",
    "Collège communautaire du Nouveau-Brunswick",
    "Crandall University",
    "Eastern College",
    "Kingswood University",
    "Maritime College of Forest Technology",
    "McKenzie College",
    "Moncton Flight College",
    "New Brunswick College of Craft and Design",
    "New Brunswick Community College",
    "Oulton College",
    "St. Thomas University",
    "St. Stephen's University",
    "University of New Brunswick"
  ],
  NewfoundlandLabrador: [
    "Centre for Nursing Studies",
    "College of the North Atlantic",
    "Keyin College",
    "Memorial University of Newfoundland",
    "Queen's College",
    "Western Regional School of Nursing"
  ],
  NovaScotia: [
    "Acadia University",
    "Cape Breton University",
    "Dalhousie University",
    "King's College",
    "Mount Saint Vincent University",
    "Nova Scotia College of Art and Design",
    "Saint Mary's University",
    "St. Francis Xavier University",
    "Université Sainte-Anne",
    "University College of Cape Breton",
    "University of King's College"
  ],
  Ontario: [
    "Algonquin College",
    "Brescia University College",
    "Brock University",
    "Carleton University",
    "Centennial College",
    "Collège Boréal",
    "Conestoga College",
    "Confederation College",
    "Durham College",
    "Fanshawe College",
    "Fleming College",
    "George Brown College",
    "Georgian College",
    "Humber College",
    "King's University College",
    "La Cité collégiale",
    "Lambton College",
    "Loyalist College",
    "McMaster University",
    "Mohawk College",
    "Nipissing University",
    "Niagara College",
    "Northern College",
    "OCAD University",
    "Queen's University",
    "Redeemer University College",
    "Royal Military College of Canada",
    "Ryerson University",
    "Seneca College",
    "Sheridan College",
    "St. Jerome's University",
    "St. Paul's University",
    "Trent University",
    "University of Guelph",
    "University of Ontario Institute of Technology",
    "University of Ottawa",
    "University of St. Michael's College",
    "University of Sudbury",
    "University of Toronto",
    "University of Waterloo",
    "University of Western Ontario",
    "University of Windsor",
    "Victoria University",
    "Wilfrid Laurier University",
    "York University"
  ],
  PrinceEdwardIsland: [
    "University of Prince Edward Island"
  ],
  Quebec: [
    "Bishop's University",
    "Collège militaire royal du Canada",
    "Collège universitaire dominicain",
    "Concordia University",
    "École de technologie supérieure",
    "École nationale d'administration publique",
    "École Polytechnique de Montréal",
    "HEC Montréal",
    "Institut national de la recherche scientifique",
    "McGill University",
    "Polytechnique Montréal",
    "TÉLUQ",
    "Université Laval",
    "Université de Montréal",
    "Université de Sherbrooke",
    "Université du Québec",
    "Université du Québec à Chicoutimi",
    "Université du Québec à Montréal",
    "Université du Québec à Rimouski",
    "Université du Québec à Trois-Rivières",
    "Université du Québec en Abitibi-Témiscamingue",
    "Université du Québec en Outaouais"
  ],
  Saskatchewan: [
    "Campion College",
    "First Nations University of Canada",
    "Luther College",
    "Saskatchewan Indian Federated College",
    "St. Thomas More College",
    "The King's University",
    "University of Regina",
    "University of Saskatchewan"
  ]
};

const universities = {
  Alberta: [
    "Ambrose University",
    "Athabasca University",
    "Burman University",
    "Canadian University College",
    "Concordia University College of Alberta",
    "King's University College",
    "MacEwan University",
    "Mount Royal University",
    "Northern Alberta Institute of Technology",
    "Red Deer Polytechnic",
    "Southern Alberta Institute of Technology",
    "University of Alberta",
    "University of Calgary",
    "University of Lethbridge"
  ],
  BritishColumbia: [
    "British Columbia Institute of Technology",
    "Capilano University",
    "Emily Carr University of Art + Design",
    "Kwantlen Polytechnic University",
    "Langara College",
    "North Island College",
    "Northern Lights College",
    "Okanagan College",
    "Selkirk College",
    "Thompson Rivers University",
    "Trinity Western University",
    "University of British Columbia",
    "University of Northern British Columbia",
    "University of the Fraser Valley",
    "University of Victoria",
    "Vancouver Island University"
  ],
  Manitoba: [
    "Assiniboine Community College",
    "Booth University College",
    "Brandon University",
    "Canadian Mennonite University",
    "Manitoba Institute of Trades and Technology",
    "Red River College Polytechnic",
    "Robertson College",
    "St. Andrew's College",
    "St. Paul's College",
    "University College of the North",
    "University of Manitoba",
    "University of Winnipeg"
  ],
  NewBrunswick: [
    "Atlantic Business College",
    "Canadian School of Natural Nutrition",
    "Collège communautaire du Nouveau-Brunswick",
    "Crandall University",
    "Eastern College",
    "Kingswood University",
    "Maritime College of Forest Technology",
    "McKenzie College",
    "Moncton Flight College",
    "New Brunswick College of Craft and Design",
    "New Brunswick Community College",
    "Oulton College",
    "St. Thomas University",
    "St. Stephen's University",
    "University of New Brunswick"
  ],
  NewfoundlandLabrador: [
    "Centre for Nursing Studies",
    "College of the North Atlantic",
    "Keyin College",
    "Memorial University of Newfoundland",
    "Queen's College",
    "Western Regional School of Nursing"
  ],
  NovaScotia: [
    "Acadia University",
    "Cape Breton University",
    "Dalhousie University",
    "King's College",
    "Mount Saint Vincent University",
    "Nova Scotia College of Art and Design",
    "Saint Mary's University",
    "St. Francis Xavier University",
    "Université Sainte-Anne",
    "University College of Cape Breton",
    "University of King's College"
  ],
  Ontario: [
    "Algonquin College",
    "Brescia University College",
    "Brock University",
    "Carleton University",
    "Centennial College",
    "Collège Boréal",
    "Conestoga College",
    "Confederation College",
    "Durham College",
    "Fanshawe College",
    "Fleming College",
    "George Brown College",
    "Georgian College",
    "Humber College",
    "King's University College",
    "La Cité collégiale",
    "Lambton College",
    "Loyalist College",
    "McMaster University",
    "Mohawk College",
    "Nipissing University",
    "Niagara College",
    "Northern College",
    "OCAD University",
    "Queen's University",
    "Redeemer University College",
    "Royal Military College of Canada",
    "Ryerson University",
    "Seneca College",
    "Sheridan College",
    "St. Jerome's University",
    "St. Paul's University",
    "Trent University",
    "University of Guelph",
    "University of Ontario Institute of Technology",
    "University of Ottawa",
    "University of St. Michael's College",
    "University of Sudbury",
    "University of Toronto",
    "University of Waterloo",
    "University of Western Ontario",
    "University of Windsor",
    "Victoria University",
    "Wilfrid Laurier University",
    "York University"
  ],
  PrinceEdwardIsland: [
    "University of Prince Edward Island"
  ],
  Quebec: [
    "Bishop's University",
    "Collège militaire royal du Canada",
    "Collège universitaire dominicain",
    "Concordia University",
    "École de technologie supérieure",
    "École nationale d'administration publique",
    "École Polytechnique de Montréal",
    "HEC Montréal",
    "Institut national de la recherche scientifique",
    "McGill University",
    "Polytechnique Montréal",
    "TÉLUQ",
    "Université Laval",
    "Université de Montréal",
    "Université de Sherbrooke",
    "Université du Québec",
    "Université du Québec à Chicoutimi",
    "Université du Québec à Montréal",
    "Université du Québec à Rimouski",
    "Université du Québec à Trois-Rivières",
    "Université du Québec en Abit"
]}
 
export { colleges, universities };